### ISSUE TITLE
[Building error]

### ISSUE THREAD

**Issue by yingnierxiao** [SakuraEngine/SakuraEngine#219]
[ 16%]: compiling.debug build\.gens\SkrAnimTool\windows\x64\debug\modules\tools\animation_tool\src\pch.hpp
error: Traceback (most recent call last):
  File "G:\gameEng\SakuraEngine\tools\meta_codegen\codegen.py", line 27, in <module>
    generate_manager.load_database()
  File "G:\gameEng\SakuraEngine/tools/meta_codegen\framework\generator.py", line 202, in load_database
    self.__database.load(require_include_dbs, self.__config)
  File "G:\gameEng\SakuraEngine/tools/meta_codegen\framework\database.py", line 193, in load
    self.main_module.load(config.main_module, config)
  File "G:\gameEng\SakuraEngine/tools/meta_codegen\framework\database.py", line 158, in load
    db.load_header(meta_file, config)
  File "G:\gameEng\SakuraEngine/tools/meta_codegen\framework\database.py", line 53, in load_header
    raw_json = json.load(f, object_pairs_hook=sc.json_object_pairs_hook)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 359, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 373 (char 372)

**Comment by SaeruHikari** [comment]
dev 暂时不稳定，需要遮罩掉一些目标才能通过编译。可以切换到 v8 分支编译。
